// Auto generated file, do not edit directly

#ifndef CANLIB_MESSAGE_TYPES_H
#define CANLIB_MESSAGE_TYPES_H

// Message Priority
typedef enum {
    PRIO_HIGHEST = 0x0,
    PRIO_HIGH = 0x1,
    PRIO_MEDIUM = 0x2,
    PRIO_LOW = 0x3,
} can_msg_prio_t;

// Message Types
typedef enum {
    MSG_GENERAL_BOARD_STATUS = 0x001,
    MSG_RESET_CMD = 0x002,
    MSG_DEBUG_RAW = 0x003,
    MSG_CONFIG_SET = 0x004,
    MSG_CONFIG_STATUS = 0x005,
    MSG_ACTUATOR_CMD = 0x006,
    MSG_ACTUATOR_ANALOG_CMD = 0x007,
    MSG_ACTUATOR_STATUS = 0x008,
    MSG_ALT_ARM_CMD = 0x009,
    MSG_ALT_ARM_STATUS = 0x00A,
    MSG_SENSOR_TEMP = 0x00B,
    MSG_SENSOR_ALTITUDE = 0x00C,
    MSG_SENSOR_IMU_X = 0x00D,
    MSG_SENSOR_IMU_Y = 0x00E,
    MSG_SENSOR_IMU_Z = 0x00F,
    MSG_SENSOR_MAG_X = 0x010,
    MSG_SENSOR_MAG_Y = 0x011,
    MSG_SENSOR_MAG_Z = 0x012,
    MSG_SENSOR_BARO = 0x013,
    MSG_SENSOR_ANALOG = 0x014,
    MSG_GPS_TIMESTAMP = 0x015,
    MSG_GPS_LATITUDE = 0x016,
    MSG_GPS_LONGITUDE = 0x017,
    MSG_GPS_ALTITUDE = 0x018,
    MSG_GPS_INFO = 0x019,
    MSG_STATE_EST_DATA = 0x01A,
    MSG_LEDS_ON = 0x01B,
    MSG_LEDS_OFF = 0x01C,
    MSG_ID_ENUM_MAX = 0x01D,
} can_msg_type_t;

// Board Type IDs
typedef enum {
    BOARD_TYPE_ID_ANY = 0x00,
    BOARD_TYPE_ID_INJ_SENSOR = 0x01,
    BOARD_TYPE_ID_CANARD_MOTOR = 0x02,
    BOARD_TYPE_ID_CAMERA = 0x03,
    BOARD_TYPE_ID_POWER = 0x04,
    BOARD_TYPE_ID_LOGGER = 0x05,
    BOARD_TYPE_ID_PROCESSOR = 0x06,
    BOARD_TYPE_ID_TELEMETRY = 0x07,
    BOARD_TYPE_ID_GPS = 0x08,
    BOARD_TYPE_ID_SRAD_GNSS = 0x09,
    BOARD_TYPE_ID_ALTIMETER = 0x0A,
    BOARD_TYPE_ID_ARMING = 0x0B,
    BOARD_TYPE_ID_PAY_SENSOR = 0x40,
    BOARD_TYPE_ID_PAY_MOTOR = 0x41,
    BOARD_TYPE_ID_RLCS_GLS = 0x80,
    BOARD_TYPE_ID_RLCS_RELAY = 0x81,
    BOARD_TYPE_ID_RLCS_HEATING = 0x82,
    BOARD_TYPE_ID_DAQ = 0x83,
    BOARD_TYPE_ID_CHARGING = 0x84,
    BOARD_TYPE_ID_THERMOCOUPLE = 0x85,
    BOARD_TYPE_ID_USB = 0x86,
    BOARD_TYPE_ID_FYDP25_TVCA = 0xC0,
} can_board_type_id_t;

// Board Instance IDs
typedef enum {
    BOARD_INST_ID_ANY = 0x00,
    BOARD_INST_ID_GENERIC = 0x01,
} can_board_inst_id_t;

typedef enum {
    BOARD_INST_ID_CANARD_MOTOR_PRIMARY = 0x02,
    BOARD_INST_ID_CANARD_MOTOR_FAILSAFE = 0x03,
} can_board_inst_id_canard_motor_t;

typedef enum {
    BOARD_INST_ID_CAMERA_INJ_A = 0x04,
    BOARD_INST_ID_CAMERA_INJ_B = 0x05,
    BOARD_INST_ID_CAMERA_VENT_A = 0x06,
    BOARD_INST_ID_CAMERA_VENT_B = 0x07,
    BOARD_INST_ID_CAMERA_VENT_C = 0x08,
    BOARD_INST_ID_CAMERA_VENT_D = 0x09,
    BOARD_INST_ID_CAMERA_RECOVERY = 0x0A,
} can_board_inst_id_camera_t;

typedef enum {
    BOARD_INST_ID_POWER_ROCKET = 0x0B,
    BOARD_INST_ID_POWER_PAYLOAD = 0x0C,
} can_board_inst_id_power_t;

typedef enum {
    BOARD_INST_ID_THERMOCOUPLE_1 = 0x0D,
    BOARD_INST_ID_THERMOCOUPLE_2 = 0x0E,
    BOARD_INST_ID_THERMOCOUPLE_3 = 0x0F,
    BOARD_INST_ID_THERMOCOUPLE_4 = 0x10,
} can_board_inst_id_thermocouple_t;

typedef enum {
    ACTUATOR_OX_INJECTOR_VALVE = 0x00,
    ACTUATOR_FUEL_INJECTOR_VALVE = 0x01,
    ACTUATOR_CHARGE_ENABLE = 0x02,
    ACTUATOR_5V_RAIL_ROCKET = 0x03,
    ACTUATOR_5V_RAIL_PAYLOAD = 0x04,
    ACTUATOR_TELEMETRY = 0x05,
    ACTUATOR_CAMERA_INJ_A = 0x06,
    ACTUATOR_CAMERA_INJ_B = 0x07,
    ACTUATOR_CAMERA_VENT_A = 0x08,
    ACTUATOR_CAMERA_VENT_B = 0x09,
    ACTUATOR_CAMERA_VENT_C = 0x0A,
    ACTUATOR_CAMERA_VENT_D = 0x0B,
    ACTUATOR_CAMERA_RECOVERY = 0x0C,
    ACTUATOR_PROC_ESTIMATOR_INIT = 0x0D,
    ACTUATOR_CANARD_ENABLE = 0x0E,
    ACTUATOR_CANARD_ANGLE = 0x0F,
    ACTUATOR_ENUM_MAX = 0x10,
} can_actuator_id_t;

typedef enum {
    ACT_STATE_ON = 0x00,
    ACT_STATE_OFF = 0x01,
    ACT_STATE_UNK = 0x02,
    ACT_STATE_ILLEGAL = 0x03,
    ACT_STATE_ENUM_MAX = 0x04,
} can_actuator_state_t;

typedef enum {
    ALTIMETER_RAVEN = 0x00,
    ALTIMETER_STRATOLOGGER = 0x01,
    ALTIMETER_SRAD = 0x02,
    ALTIMETER_ENUM_MAX = 0x03,
} can_altimeter_id_t;

typedef enum {
    ALT_ARM_STATE_DISARMED = 0x00,
    ALT_ARM_STATE_ARMED = 0x01,
    ALT_ARM_STATE_ENUM_MAX = 0x02,
} can_alt_arm_state_t;

typedef enum {
    IMU_PROC_ALTIMU10 = 0x00,
    IMU_PROC_MTI630 = 0x01,
    IMU_PROC_LSM6DSO32 = 0x02,
    IMU_SRAD_ALT_ALTIMU10 = 0x03,
    IMU_ENUM_MAX = 0x04,
} can_imu_id_t;

typedef enum {
    SENSOR_5V_VOLT = 0x00,
    SENSOR_5V_CURR = 0x01,
    SENSOR_12V_VOLT = 0x02,
    SENSOR_12V_CURR = 0x03,
    SENSOR_CHARGE_VOLT = 0x04,
    SENSOR_CHARGE_CURR = 0x05,
    SENSOR_BATT_VOLT = 0x06,
    SENSOR_BATT_CURR = 0x07,
    SENSOR_MOTOR_CURR = 0x08,
    SENSOR_PRESSURE_OX = 0x09,
    SENSOR_PRESSURE_FUEL = 0x0A,
    SENSOR_PRESSURE_CC = 0x0B,
    SENSOR_BARO_PRESSURE = 0x0C,
    SENSOR_BARO_TEMP = 0x0D,
    SENSOR_RA_BATT_VOLT_1 = 0x0E,
    SENSOR_RA_BATT_VOLT_2 = 0x0F,
    SENSOR_RA_BATT_CURR_1 = 0x10,
    SENSOR_RA_BATT_CURR_2 = 0x11,
    SENSOR_RA_MAG_VOLT_1 = 0x12,
    SENSOR_RA_MAG_VOLT_2 = 0x13,
    SENSOR_FPS = 0x14,
    SENSOR_CANARD_ENCODER_1 = 0x15,
    SENSOR_CANARD_ENCODER_2 = 0x16,
    SENSOR_PROC_FLIGHT_PHASE_STATUS = 0x17,
    SENSOR_VELOCITY = 0x18,
    SENSOR_ENUM_MAX = 0x19,
    SENSOR_HALL_FUEL_INJ = 0x1A,
    SENSOR_HALL_OX_INJ = 0x1B,
} can_analog_sensor_id_t;

typedef enum {
    STATE_ID_ATT_Q0 = 0x00,
    STATE_ID_ATT_Q1 = 0x01,
    STATE_ID_ATT_Q2 = 0x02,
    STATE_ID_ATT_Q3 = 0x03,
    STATE_ID_RATE_WX = 0x04,
    STATE_ID_RATE_WY = 0x05,
    STATE_ID_RATE_WZ = 0x06,
    STATE_ID_VEL_VX = 0x07,
    STATE_ID_VEL_VY = 0x08,
    STATE_ID_VEL_VZ = 0x09,
    STATE_ID_ALT = 0x0A,
    STATE_ID_COEFF_CL = 0x0B,
    STATE_ID_CANARD_ANGLE = 0x0C,
    STATE_ID_ENUM_MAX = 0x0D,
} can_state_est_id_t;

typedef enum {
    E_5V_OVER_CURRENT_OFFSET = 0x00,
    E_5V_OVER_VOLTAGE_OFFSET = 0x01,
    E_5V_UNDER_VOLTAGE_OFFSET = 0x02,
    E_12V_OVER_CURRENT_OFFSET = 0x03,
    E_12V_OVER_VOLTAGE_OFFSET = 0x04,
    E_12V_UNDER_VOLTAGE_OFFSET = 0x05,
    E_IO_ERROR_OFFSET = 0x06,
    E_FS_ERROR_OFFSET = 0x07,
    E_PT_OUT_OF_RANGE = 0x08,
} can_general_board_status_offset_t;

#endif
