// Auto generated file, do not edit directly

#ifndef CANLIB_MESSAGE_TYPES_H
#define CANLIB_MESSAGE_TYPES_H

// Message Priority
typedef enum {
	PRIO_HIGHEST = 0x0,
	PRIO_HIGH = 0x1,
	PRIO_MEDIUM = 0x2,
	PRIO_LOW = 0x3
} can_msg_prio_t;

// Message Types
typedef enum {
	MSG_UNDEFINED = 0x000,
	MSG_GENERAL_BOARD_STATUS = 0x001,
	MSG_RESET_CMD = 0x002,
	MSG_DEBUG_RAW = 0x003,
	MSG_CONFIG_SET = 0x004,
	MSG_CONFIG_STATUS = 0x005,
	MSG_ACTUATOR_CMD = 0x006,
	MSG_ACTUATOR_STATUS = 0x007,
	MSG_ALT_ARM_CMD = 0x008,
	MSG_ALT_ARM_STATUS = 0x009,
	MSG_SENSOR_ANALOG16 = 0x00A,
	MSG_SENSOR_ANALOG32 = 0x00B,
	MSG_SENSOR_DEM_ANALOG16 = 0x00C,
	MSG_GPS_TIMESTAMP = 0x00D,
	MSG_GPS_LATITUDE = 0x00E,
	MSG_GPS_LONGITUDE = 0x00F,
	MSG_GPS_ALTITUDE = 0x010,
	MSG_GPS_INFO = 0x011,
	MSG_STREAM_STATUS = 0x012,
	MSG_STREAM_DATA = 0x013,
	MSG_STREAM_RETRY = 0x014,
	MSG_LEDS_ON = 0x015,
	MSG_LEDS_OFF = 0x016,
	MSG_ID_ENUM_MAX = 0x017
} can_msg_type_t;

// Board Type IDs
typedef enum {
	BOARD_TYPE_ID_ANY = 0x00,
	BOARD_TYPE_ID_INJECTOR = 0x01,
	BOARD_TYPE_ID_CAMERA = 0x02,
	BOARD_TYPE_ID_POWER = 0x03,
	BOARD_TYPE_ID_LOGGER = 0x04,
	BOARD_TYPE_ID_CANARD = 0x05,
	BOARD_TYPE_ID_TELEMETRY = 0x06,
	BOARD_TYPE_ID_GPS = 0x07,
	BOARD_TYPE_ID_ALTIMETER = 0x08,
	BOARD_TYPE_ID_ARMING = 0x09,
	BOARD_TYPE_ID_PAYLOAD = 0x0A,
	BOARD_TYPE_ID_RLCS_GLS = 0x0B,
	BOARD_TYPE_ID_RLCS_RELAY = 0x0C,
	BOARD_TYPE_ID_DAQ = 0x0D,
	BOARD_TYPE_ID_ENUM_MAX = 0x0E
} can_board_type_id_t;

// Board Instance IDs
typedef enum {
	BOARD_INST_ID_ANY = 0x00,
	BOARD_INST_ID_GROUND = 0x01,
	BOARD_INST_ID_ROCKET = 0x02,
	BOARD_INST_ID_PAYLOAD = 0x03
} can_board_inst_id_t;

typedef enum {
	BOARD_INST_ID_CAMERA_SIDE_LOOKING = 0x04,
	BOARD_INST_ID_CAMERA_DOWN_LOOKING = 0x05,
	BOARD_INST_ID_CAMERA_RECOVERY = 0x06,
	BOARD_INST_ID_CAMERA_ENUM_MAX = 0x07
} can_board_inst_id_camera_t;

typedef enum {
	BOARD_INST_ID_ARMING_RA_RAVEN = 0x07,
	BOARD_INST_ID_ARMING_RA_STRATOLOGGER = 0x08,
	BOARD_INST_ID_ARMING_ENUM_MAX = 0x09
} can_board_inst_id_arming_t;

typedef enum {
	ACTUATOR_OX_INJECTOR_VALVE = 0x00,
	ACTUATOR_FUEL_INJECTOR_VALVE = 0x01,
	ACTUATOR_ROCKET_CHARGE_ENABLE = 0x02,
	ACTUATOR_PAYLOAD_CHARGE_ENABLE = 0x03,
	ACTUATOR_5V_RAIL_ROCKET = 0x04,
	ACTUATOR_5V_RAIL_PAYLOAD = 0x05,
	ACTUATOR_12V_RAIL_ROCKET = 0x06,
	ACTUATOR_TELEMETRY = 0x07,
	ACTUATOR_CAMERA_SIDE_LOOKING = 0x08,
	ACTUATOR_CAMERA_DOWN_LOOKING = 0x09,
	ACTUATOR_CAMERA_RECOVERY = 0x0A,
	ACTUATOR_CANARD_PAD_FILTER = 0x0B,
	ACTUATOR_CANARD_LOW_POWER_MODE = 0x0C,
	ACTUATOR_SRAD_ALT_ESTIMATOR_INIT = 0x0D,
	ACTUATOR_SRAD_ALT_GPS_RESET = 0x0E,
	ACTUATOR_CAMERA_CAPTURE = 0x0F,
	ACTUATOR_PAYLOAD_LOGGING_ENABLE = 0x10,
	ACTUATOR_THESEUS_ACTUATOR_1 = 0x11,
	ACTUATOR_THESEUS_ACTUATOR_2 = 0x12,
	ACTUATOR_RLCS_RELAY_POWER = 0x13,
	ACTUATOR_RLCS_RELAY_SELECT = 0x14,
	ACTUATOR_ENUM_MAX = 0x15
} can_actuator_id_t;

typedef enum {
	ACT_STATE_ON = 0x00,
	ACT_STATE_OFF = 0x01,
	ACT_STATE_UNK = 0x02,
	ACT_STATE_ILLEGAL = 0x03,
	ACT_STATE_ENUM_MAX = 0x04
} can_actuator_state_t;

typedef enum {
	ALTIMETER_RAVEN = 0x00,
	ALTIMETER_STRATOLOGGER = 0x01,
	ALTIMETER_SRAD = 0x02,
	ALTIMETER_ENUM_MAX = 0x03
} can_altimeter_id_t;

typedef enum {
	ALT_ARM_STATE_DISARMED = 0x00,
	ALT_ARM_STATE_ARMED = 0x01,
	ALT_ARM_STATE_ENUM_MAX = 0x02
} can_alt_arm_state_t;

typedef enum {
	SENSOR_5V_VOLT = 0x00,
	SENSOR_5V_CURR = 0x01,
	SENSOR_12V_VOLT = 0x02,
	SENSOR_12V_CURR = 0x03,
	SENSOR_CHARGE_VOLT = 0x04,
	SENSOR_CHARGE_CURR = 0x05,
	SENSOR_BATT_VOLT = 0x06,
	SENSOR_BATT_CURR = 0x07,
	SENSOR_RADIO_CURR = 0x08,
	SENSOR_GPS_CURR = 0x09,
	SENSOR_LOCAL_CURR = 0x0A,
	SENSOR_PT_CHANNEL_1 = 0x0B,
	SENSOR_PT_CHANNEL_2 = 0x0C,
	SENSOR_PT_CHANNEL_3 = 0x0D,
	SENSOR_PT_CHANNEL_4 = 0x0E,
	SENSOR_PT_CHANNEL_5 = 0x0F,
	SENSOR_HALL_CHANNEL_1 = 0x10,
	SENSOR_HALL_CHANNEL_2 = 0x11,
	SENSOR_HALL_CHANNEL_3 = 0x12,
	SENSOR_RA_BATT_VOLT_1 = 0x13,
	SENSOR_RA_BATT_VOLT_2 = 0x14,
	SENSOR_RA_BATT_CURR_1 = 0x15,
	SENSOR_RA_BATT_CURR_2 = 0x16,
	SENSOR_RA_MAG_VOLT_1 = 0x17,
	SENSOR_RA_MAG_VOLT_2 = 0x18,
	SENSOR_FPS = 0x19,
	SENSOR_PAYLOAD_LIM_1 = 0x1A,
	SENSOR_PAYLOAD_LIM_2 = 0x1B,
	SENSOR_PAYLOAD_SERVO_DIRECTION = 0x1C,
	SENSOR_PAYLOAD_INFRARED = 0x1D,
	SENSOR_THESEUS_TEMP_1 = 0x1E,
	SENSOR_THESEUS_TEMP_2 = 0x1F,
	SENSOR_THESEUS_TEMP_3 = 0x20,
	SENSOR_RLCS_RELAY_OUTPUT_VOLT_A = 0x21,
	SENSOR_RLCS_RELAY_OUTPUT_VOLT_B = 0x22,
	SENSOR_RLCS_RELAY_OUTPUT_CURR_A = 0x23,
	SENSOR_RLCS_RELAY_OUTPUT_CURR_B = 0x24,
	SENSOR_RLCS_RELAY_LIM_VOLT_A = 0x25,
	SENSOR_RLCS_RELAY_LIM_VOLT_B = 0x26,
	SENSOR_LOG_WRITTEN_SIZE = 0x27,
	SENSOR_SD_LOG_FILE_NAME = 0x28,
	SENSOR_SD_USED = 0x29,
	SENSOR_SD_FREE = 0x2A,
	SENSOR_FLASH_LOG_FILE_NAME = 0x2B,
	SENSOR_FLASH_USED = 0x2C,
	SENSOR_FLASH_FREE = 0x2D,
	SENSOR_CANARD_CTRL_CMD_ANGLE = 0x2E,
	SENSOR_CANARD_CTRL_COEFF_LIFT = 0x2F,
	SENSOR_CANARD_MS5611_BARO = 0x30,
	SENSOR_CANARD_MS5611_TEMP = 0x31,
	SENSOR_CANARD_MTI630_BARO_0 = 0x32,
	SENSOR_CANARD_MTI630_BARO_1 = 0x33,
	SENSOR_CANARD_MTI630_EST_ALT = 0x34,
	SENSOR_CANARD_ADXRS649_GYRO = 0x35,
	SENSOR_CANARD_SERVO_ANGLE = 0x36,
	SENSOR_CANARD_SERVO_CURR = 0x37,
	SENSOR_CANARD_SERVO_TEMP = 0x38,
	SENSOR_ENUM_MAX = 0x39
} can_analog_sensor_id_t;

typedef enum {
	DEM_SENSOR_CANARD_NAV_ORIENTATION_QUAT_QX_QY_QZ = 0x00,
	DEM_SENSOR_CANARD_NAV_ORIENTATION_QUAT_QW_ALT_VARNORM = 0x01,
	DEM_SENSOR_CANARD_NAV_ANGLE_VEL = 0x02,
	DEM_SENSOR_CANARD_NAV_VEL = 0x03,
	DEM_SENSOR_CANARD_LSM6DSV32X_ACCEL = 0x04,
	DEM_SENSOR_CANARD_LSM6DSV32X_GYRO = 0x05,
	DEM_SENSOR_CANARD_LSM303AGR_ACCEL = 0x06,
	DEM_SENSOR_CANARD_LSM303AGR_MAG = 0x07,
	DEM_SENSOR_CANARD_MTI630_ACCEL = 0x08,
	DEM_SENSOR_CANARD_MTI630_GYRO = 0x09,
	DEM_SENSOR_CANARD_MTI630_MAG = 0x0A,
	DEM_SENSOR_CANARD_MTI630_EST_ORIENTATION = 0x0B,
	DEM_SENSOR_CANARD_MTI630_EST_ANGLE_VEL = 0x0C,
	DEM_SENSOR_CANARD_MTI630_EST_VEL = 0x0D,
	DEM_SENSOR_CANARD_ADXL380_ACCEL = 0x0E,
	DEM_SENSOR_ENUM_MAX = 0x0F
} can_dem_sensor_id_t;

typedef enum {
	E_5V_OVER_CURRENT_OFFSET = 0x00,
	E_5V_OVER_VOLTAGE_OFFSET = 0x01,
	E_5V_UNDER_VOLTAGE_OFFSET = 0x02,
	E_12V_OVER_CURRENT_OFFSET = 0x03,
	E_12V_OVER_VOLTAGE_OFFSET = 0x04,
	E_12V_UNDER_VOLTAGE_OFFSET = 0x05,
	E_BATT_OVER_CURRENT_OFFSET = 0x06,
	E_BATT_OVER_VOLTAGE_OFFSET = 0x07,
	E_BATT_UNDER_VOLTAGE_OFFSET = 0x08,
	E_MOTOR_OVER_CURRENT_OFFSET = 0x09,
	E_IO_ERROR_OFFSET = 0x0A,
	E_FS_ERROR_OFFSET = 0x0B,
	E_WATCHDOG_TIMEOUT_OFFSET = 0x0C,
	E_GENERAL_BOARD_STATUS_OFFSET_MAX = 0x0D
} can_general_board_status_offset_t;

typedef enum {
	E_12V_EFUSE_FAULT_OFFSET = 0x00,
	E_5V_EFUSE_FAULT_OFFSET = 0x01,
	E_PT_OUT_OF_RANGE_OFFSET = 0x02,
	E_BOARD_SPECIFIC_STATUS_OFFSET_MAX = 0x03
} can_board_specific_status_offset_t;

#endif
