#ifndef CANLIB_PIC18F26K83_CAN_H
#define CANLIB_PIC18F26K83_CAN_H

#include <stdbool.h>

#include "can.h"

#ifdef __cplusplus
#error "C++ is not supported"
#endif

/**
 * @brief Initialize PIC18F26K83 CAN Controller
 *
 * @param timing Timing parameters generated by `can_generate_timing_params` function
 * @param receive_callback CAN message receive handler, the function would be called when a CAN
 * message is received
 *
 * @warning Note that this function DOES NOT setup the inputs and outputs from the CAN module to the
 * output pins, application code must do that. In order to do that, CANRXPPS must be set to the
 * proper pin value for the CANRX pin, and ___PPS must be set to 0x33 to mark it as outputting from
 * the CAN module. In addition, TRIS and ANSEL registers for whatever pin is being used must be set
 * to the right values.
 */
void pic18f26k83_can_init(const can_timing_t *timing,
						  void (*receive_callback)(const can_msg_t *message));

/**
 * @brief Send a CAN message
 *
 * @param message CAN message to be sent
 */
void pic18f26k83_can_send(const can_msg_t *message);

/**
 * @brief Check if CAN controller is ready to send a message
 *
 * @return return `true` if ready to send a message
 */
bool pic18f26k83_can_send_rdy(void);

/**
 * @brief Call this function in an interrupt context whenever PIR5 is nonzero
 *
 * @note This function clears PIR5 interrupt flags
 */
void pic18f26k83_can_handle_interrupt(void);

#endif // compile guard
