#ifndef CANLIB_CANARDS_H
#define CANLIB_CANARDS_H

#include <stdbool.h>
#include <stdint.h>

#include "common.h"

#include "can.h"
#include "message_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * @brief Builda a canard module status message.
 *
 * @param prio Message priority
 * @param timestamp Message timestamp generated by millis() function
 * @param module_id Module ID. Encoded in the SID metadata field
 * @param error_bitfield Error Code Bitfield
 * @param severity Error severity
 * @param output Output message buffer
 */
void build_canard_firmware_error_msg(can_msg_prio_t prio, uint16_t timestamp, uint8_t module_id,
									 uint32_t error_bitfield, uint8_t severity, can_msg_t *output);

/*
 * @brief Pack a CANARD_FIRMWARE_ERROR message
 *
 * @param msg Input message buffer
 * @param module_id Module ID
 * @param error_bitfield Error Code Bitfield
 * @param severity Error severity
 *
 * @return true if message parsed successfully, false if message has format error
 */
w_status_t get_canard_firmware_error_msg(const can_msg_t *msg, uint8_t *module_id,
										 uint32_t *error_bitfield, uint8_t *severity);

#ifdef __cplusplus
}
#endif

#endif
