#ifndef CANLIB_TELEMETRY_H
#define CANLIB_TELEMETRY_H

#include <stdbool.h>
#include <stdint.h>

#include "common.h"

#include "can.h"
#include "message_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * @brief Send telemetry info message.
 *
 * @param prio Message priority
 * @param timestamp Message timestamp generated by millis() function
 * @param channel_id Channel ID (Use LTT board instance ID). Encoded in the SID metadata field
 * @param lqi Link Quality Indicator
 * @param rssi Received Signal Strength Indicator
 * @param output Output message buffer
 */
void build_telemetry_info_msg(can_msg_prio_t prio, uint16_t timestamp, uint8_t channel_id,
							  uint8_t lqi, uint8_t rssi, can_msg_t *output);

/*
 * @brief Pack a TELEMETRY_INFO message from 3 8-bits unsigned integer
 *
 * @param msg Input message buffer
 * @param module_id Module ID
 * @param error_bitfield Error Code Bitfield
 * @param severity Error severity
 *
 * @return true if message parsed successfully, false if message has format error
 */
w_status_t get_telemetry_info_msg(const can_msg_t *msg, uint8_t *channel_id, uint8_t *lqi,
								  uint8_t *rssi);

#ifdef __cplusplus
}
#endif

#endif
