name: C Coding Style Check

# Runs on pushes to pull request
on: pull_request

jobs:
  # Build job
  clang-format-style-check:
    name: C Coding Style Check (clang-format check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Install clang-format 21
        id: llvm-install
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install clang-format-21
      - name: Run format check
        id: run-format-check
        shell: bash
        run: make format-check CLANG_FORMAT=clang-format-21
